### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tokunagatensei** [tokunagatensei/furima-38891#20]
# フリマアプリのURL
https://furima-38891.onrender.com/

# Basic認証のIDとパスワード
ID : secret      パスワード : 12345

# 出品者用のメールアドレスとパスワード
メールアドレス : test@com          パスワード : test111

# 購入者用のメールアドレスとパスワード
メールアドレス : test2@com        パスワード : test111

**Comment by snkw-works** [comment]
@tokunagatensei さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作確認させて頂いたところ、Basic認証のIDとパスワードを入力後にエラーが発生するため、TOPページを表示することができない状態です。
本番環境の動作だけではエラーの詳しい原因までは判断しかねる為、renderのエラーログをご確認いただき修正をお願い致します。
エラーログを確認しても原因が特定出来ない場合はコネクトにてご質問頂きますようお願い致します。

<img width="710" alt="スクリーンショット 2023-02-20 9 24 45" src="https://user-images.githubusercontent.com/54050089/219990959-e5340a75-44ee-4ef9-bac7-20df129c4f40.png">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ghost** [comment]
@tokunagatensei さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。

![最終課題LGTM](https://user-images.githubusercontent.com/116065064/220237622-277a3cf4-5b82-4899-8272-8f8d666dbe75.png)
